### ISSUE TITLE
Add sub command to open the web interface

### ISSUE THREAD

**Issue by carlosms** [src-d/superset-compose#17]
From the design doc:
> As a user I want to open the web interface so that I don't need to know the exact URL/port it is running and copy and paste to my browser

I'm not sure about the implementation details, but my first proposal is to open the browser on `start`, and maybe have a new sub command (`web`?) that only does this, open the link in the browser.

**Comment by se7entyse7en** [comment]
Maybe it could make sense to also open it after `install`?

**Comment by carlosms** [comment]
Reopening because I have just realized that we have an entry for other sub commands in the README, so we should also add one for `web`.
