### ISSUE TITLE
sandbox-ce install: ctrl+c does not wait for exit

### ISSUE THREAD

**Issue by carlosms** [src-d/superset-compose#22]
Running install starts the containers, and waits for a ctrl+c.
When you press ctrl+c the command exits before docker-compose down is done, and it continues to output to stdout
```
^CGracefully stopping... (press Ctrl+C again to force)
signal: interrupt
Stopping srcd_gitbase_1    ... 
Stopping srcd_bblfsh_1     ... 
Stopping srcd_bblfsh-web_1 ... done
Stopping srcd_superset_1   ... 
Stopping srcd_gitbase_1    ... done
Stopping srcd_bblfsh_1     ... done
@cacharrin superset-compose master= $ 
Stopping srcd_superset_1   ... done
Stopping srcd_postgres_1   ... done
Stopping srcd_redis_1      ... done
@cacharrin superset-compose master= $ 
```

**Comment by se7entyse7en** [comment]
I wasn't able to reproduce it. If I press `Ctrl+C` once, then all containers are stopped and the prompt doesn't appear until it finishes. If I press `Ctrl+C` twice, then the operation is aborted, but still, the prompt doesn't appear. This is what's happening in my case when `Ctrl+C` is pressed twice:
```
^CGracefully stopping... (press Ctrl+C again to force)
Stopping srcd_superset_1   ...
Stopping srcd_gitbase_1    ...
Stopping srcd_bblfsh-web_1 ... done
Stopping srcd_postgres_1   ...
Stopping srcd_redis_1      ...
^CERROR: Aborting.
exit status 1
exit status 1
✘  se7entyse7en in ~/Projects/smacker/superset-compose (docker-compose-container)  $
```

**Comment by smacker** [comment]
Install command exits now right after `up --detach`. Most probably we don't need to fix it anymore.

**Comment by carlosms** [comment]
True, not relevant anymore.
